### PR TITLE
[breaking] scalar row indexing produces column vector

### LINKED ISSUE #509: Scalar indexing of row of matrix creates row vector, causing incorrect `dot`
```julia
julia> x = Variable(2,2)
Variable
size: (2, 2)
sign: real
vexity: affine
id: 936…769

julia> set_value!(x, ones(2,2))
2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

julia> evaluate(x[2, :])
1×2 Matrix{Float64}:
 1.0  1.0

julia> evaluate(x)[2, :]
2-element Vector{Float64}:
 1.0
 1.0
```

In particular this causes `dot` to be incorrect: https://discourse.julialang.org/t/convex-jl-constraints-not-enforced/102439/2.

### PR DESCRIPTION
**Pull request by ericphanson**
fixes #509 

There _could_ be other issues like this out there, but at least this fixes that particular one, and I can't quite think of others off the top of my head.

### CODE REVIEW

File: src/atoms/IndexAtom.jl [hunk 1]
```diff
@@ -9,18 +9,14 @@ mutable struct IndexAtom <: AbstractExpr
...
+function IndexAtom(x::AbstractExpr, rows::AbstractArray, cols::AbstractArray)
+    return IndexAtom((x,), (length(rows), length(cols)), rows, cols, nothing)
+end
 
-    function IndexAtom(x::AbstractExpr, inds::AbstractArray)
-        return new((x,), (length(inds), 1), nothing, nothing, inds)
-    end
+function IndexAtom(x::AbstractExpr, inds::AbstractArray)
+    return IndexAtom((x,), (length(inds), 1), nothing, nothing, inds)
 end
```
Comment (ericphanson) [inline src/atoms/IndexAtom.jl:20]: I made these outer constructors to not suppress the creation of the default inner constructor, so I could use it in the bugfix

**Comment by odow** [comment]
The doc failure seems suspicious.

**Comment by odow** [comment]
This isn't quite correct. Here's a reproducer from the docs:
```Julia
julia> using Convex

julia> import MathOptInterface as MOI

julia> x = Variable(2, 2)
Variable
size: (2, 2)
sign: real
vexity: affine
id: 885…241

julia> context = Convex.Context{Float64}(MOI.Utilities.Model{Float64});

julia> Y = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> Convex.to_vaf(Convex.conic_form!(context, x[1, :] .* Y[1, :]'))
┌                              ┐
│0.0 + 1.0 MOI.VariableIndex(1)│
│0.0 + 1.0 MOI.VariableIndex(3)│
│0.0 + 2.0 MOI.VariableIndex(1)│
│0.0 + 2.0 MOI.VariableIndex(3)│
└                              ┘

julia> Convex.to_vaf(Convex.conic_form!(context, x[1:1, :] .* Y[1, :]'))
┌                              ┐
│0.0 + 1.0 MOI.VariableIndex(1)│
│0.0 + 2.0 MOI.VariableIndex(3)│
└                              ┘
```

These two calls should be the same.

**Comment by odow** [comment]
Okay, perhaps the docs are wrong, because:
```Julia
julia> a = [1, 2]
2-element Vector{Int64}:
 1
 2

julia> a .* a'
2×2 Matrix{Int64}:
 1  2
 2  4
```

File: docs/src/examples/optimization_with_complex_variables/power_flow_optimization.jl [hunk 2]
```diff
@@ -18,7 +18,7 @@ W = ComplexVariable(n, n);
 objective = real(sum(diag(W)));
 c1 = Constraint[];
 for i in 2:n
-    push!(c1, sum(W[i, :] .* (Y[i, :]')) == inj[i])
+    push!(c1, sum(W[i, :] .* conj(Y[i, :])) == inj[i])
```
Comment (odow) [inline docs/src/examples/optimization_with_complex_variables/power_flow_optimization.jl:21]: Ooooofff. This is pretty subtle...

**Review by odow — APPROVED** [review]

**Review by odow — APPROVED** [review]
I think this is worth it. The next version might break existing code, but it's arguably a bug fix because the current code departs from regular Julia. There's a strong chance that any breakage is likely a bug to begin with.

File: docs/src/examples/optimization_with_complex_variables/power_flow_optimization.jl (hunk 2 above)
Comment (ericphanson) [reply docs/src/examples/optimization_with_complex_variables/power_flow_optimization.jl]: Good catch! Btw maybe this could be `dot`? It used to be bugged in the complex case so maybe the original author didn’t use it

File: src/problem_depot/problems/affine.jl [hunk 3]
```diff
@@ -280,6 +280,24 @@ end
         @test p.optval ≈ 147 atol = atol rtol = rtol
     end
 
+    # *Scalar* indexing creates a column vector
```
Comment (ericphanson) [inline src/problem_depot/problems/affine.jl:283]: This test is probably misplaced since it doesn’t use a solver

File: docs/src/examples/optimization_with_complex_variables/power_flow_optimization.jl (hunk 2 above)
Comment (odow) [reply docs/src/examples/optimization_with_complex_variables/power_flow_optimization.jl]: Updated to use `dot`. Yeah, I assume the previous code was just trial and error to find what worked.

File: src/problem_depot/problems/affine.jl (hunk 3 above)
Comment (odow) [reply src/problem_depot/problems/affine.jl:283]: I will move
