### PR TITLE
Special-case getindex on VcatAtom

### LINKED ISSUE #603: vexity(::IndexAtom) is inexact
The `vexity` of the `IndexAtom` is incorrect:
```julia
julia> x = Variable()
Variable
size: (1, 1)
sign: real
vexity: affine
id: 176…085

julia> v = vcat(x, square(x))
reshape (convex; real)
└─ * (convex; real)
   ├─ 2×2 Matrix{Bool}
   └─ reshape (convex; real)
      └─ hcat (convex; real)
         ├─ …
         └─ …

julia> vexity(v)
Convex.ConvexVexity()

julia> vexity(v[1])
Convex.ConvexVexity()

julia> v = vcat(-square(x), square(x))
reshape (Convex.NotDcp; real)
└─ * (Convex.NotDcp; real)
   ├─ 2×2 Matrix{Bool}
   └─ reshape (Convex.NotDcp; real)
      └─ hcat (Convex.NotDcp; real)
         ├─ …
         └─ …

julia> vexity(v)
Convex.NotDcp()

julia> vexity(v[1])
Convex.NotDcp()
```

### PR DESCRIPTION
**Pull request by ericphanson**
here is my attempt at #611

closes #611 
closes #603

### CODE REVIEW

File: src/atoms/VcatAtom.jl [hunk 1]
```diff
@@ -59,3 +59,81 @@ function Base.vcat(args::Union{AbstractExpr,Value}...)
...
+        else
+            l = last(I)
+            for i in eachindex(inds)
+                if inds[i] >= l
+                    inds[i] -= length(I)
+                end
+            end
+        end
+    end
+
```
Comment (odow) [inline src/atoms/VcatAtom.jl:136]:
```suggestion
```

File: src/atoms/VcatAtom.jl [hunk 2]
```diff
@@ -59,3 +59,81 @@ function Base.vcat(args::Union{AbstractExpr,Value}...)
...
+            # let's update `rows` to account for the removal
+            l = last(I)
+            for i in eachindex(rows)
+                if rows[i] >= l
+                    rows[i] -= length(I)
+                end
+            end
+        end
+    end
+
```
Comment (odow) [inline src/atoms/VcatAtom.jl:94]:
```suggestion
```

File: src/atoms/VcatAtom.jl [hunk 3]
```diff
@@ -59,3 +59,81 @@ function Base.vcat(args::Union{AbstractExpr,Value}...)
     end
     return VcatAtom(args...)
 end
```
Comment (odow) [inline src/atoms/VcatAtom.jl:61]:
```suggestion
end

```

**Review by odow — APPROVED** [review]
