### PR TITLE
Fix ambiguities found by Aqua

### LINKED ISSUE #639: Fix Aqua ambiguities
This would catch stuff like #637

### PR DESCRIPTION
**Pull request by odow**
Closes #639

### CODE REVIEW

File: src/atoms/VcatAtom.jl [hunk 1]
```diff
@@ -127,3 +127,7 @@ function Base.getindex(x::VcatAtom, inds::AbstractVector{<:Real})
     remaining = VcatAtom(keep_children...)
     return IndexAtom(remaining, inds)
 end
+
+function Base.getindex(x::VcatAtom, inds::AbstractVector{Bool})
+    return getindex(x, first.(filter!(last, collect(enumerate(inds)))))
```
Comment (ericphanson) [inline src/atoms/VcatAtom.jl:132]: I think this is just `findall` btw
